### ISSUE TITLE
How can I import your module?

### ISSUE THREAD

**Issue by cod3r0k** [khalooei/LSA#2]
Hello, I would like to import your module. However, I encountered the following error. What should I do?

```
  File "<ipython-input-32-184307e9911e>", line 2
    from layer-sustainability-analysis import LayerSustainabilityAnalysis as LSA
              ^
SyntaxError: invalid syntax
```

**Comment by khalooei** [comment]
Dear @cod3r0k , Thank you for your comments! To import LSA, you can use the latest tutorial or the following syntax.

```
pip install LayersSustainabilityAnalysis
```

For further information, please don't hesitate to contact me.
