### ISSUE TITLE
Greedy LSA (a new idea for contribution)

### ISSUE THREAD

**Issue by Obile19** [khalooei/LSA#3]
Hi, Thank you for your interesting work!
I want to integrate your work with **[Greedy Layer-Wise Training of Deep Networks](https://papers.nips.cc/paper/2006/file/5da713a690c067105aeb2fae32403405-Paper.pdf)**. Do you have any comments and ideas for its integration?

**Comment by khalooei** [comment]
Dear @Obile19 
Thank you for comment!
That's great. All you need to do is change the [layer module lines](https://github.com/khalooei/LSA/blob/e4f9e8ee08bf315aca30273a35d2b88acaf5e020/LayerSustainabilityAnalysis/layersustainabilityanalysis.py#L44)
You can contact me If you need assistance during with the integration process.
